apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  ports:
  - port: 9005
    protocol: TCP
    targetPort: 9005
  selector:
    app: mealie
  type: LoadBalancer
